export interface MenuItem  { id:string; fa:string; de:string; price:number }
export interface MenuCat   { id:string; fa:string; de:string; type:'card'|'list'|'sauces'; items:MenuItem[] }

export const MENU_CATS: MenuCat[] = [
  { id:'sandwiches', fa:'ساندویچ', de:'Sandwiches', type:'card', items:[
    {id:'sw1',  fa:'ساندویچ کوکتل پنیری',      de:'Käse-Cocktail Sandwich',       price:10  },
    {id:'sw2',  fa:'ساندویچ هایدا',             de:'Haida Sandwich',               price:10  },
    {id:'sw3',  fa:'ساندویچ بندری',             de:'Bandari Sandwich',             price:9   },
    {id:'sw4',  fa:'ساندویچ زبان تنوری با پنیر',de:'Ofenzunge mit Käse',           price:12.5},
    {id:'sw5',  fa:'ساندویچ فلافل',             de:'Falafel Sandwich',             price:7   },
    {id:'sw6',  fa:'ساندویچ آذر',               de:'Azar Sandwich',               price:15  },
    {id:'sw7',  fa:'همبرگر',                    de:'Hamburger',                    price:10  },
    {id:'sw8',  fa:'همبرگر مخصوص',              de:'Spezial Hamburger',            price:13  },
    {id:'sw9',  fa:'زبان',                      de:'Rinderzunge',                  price:12.5},
    {id:'sw10', fa:'مغز و زبان',                de:'Hirn & Rinderzunge',           price:13.5},
    {id:'sw11', fa:'ساندویچ مرغ',               de:'Hähnchen Sandwich',            price:10  },
    {id:'sw12', fa:'ساندویچ مرغ مخصوص',        de:'Spezial Hähnchen Sandwich',    price:13  },
  ]},
  { id:'pizzas', fa:'پیتزا', de:'Pizzen', type:'card', items:[
    {id:'pz1', fa:'پیتزا تهران',      de:'Pizza Teheran',           price:16},
    {id:'pz2', fa:'پیتزا شیراز',      de:'Pizza Shiraz',            price:14},
    {id:'pz3', fa:'پیتزا مرغ و قارچ', de:'Pizza Hähnchen & Pilze', price:14},
  ]},
  { id:'starters', fa:'پیش‌غذا', de:'Vorspeisen', type:'list', items:[
    {id:'st1', fa:'چیپس و پنیر',    de:'Pommes mit Käse',         price:6  },
    {id:'st2', fa:'سیب زمینی کوچک', de:'Kleine Pommes',           price:3.5},
    {id:'st3', fa:'سیب زمینی بزرگ', de:'Große Pommes',            price:5  },
    {id:'st4', fa:'سالاد چهار فصل', de:'Vier Jahreszeiten Salat', price:6  },
  ]},
  { id:'salads', fa:'سالاد', de:'Salate', type:'list', items:[
    {id:'sa1', fa:'سالاد چهار فصل',     de:'Vier Jahreszeiten Salat', price:5},
    {id:'sa2', fa:'سالاد فلافل',        de:'Falafel Salat',           price:6},
    {id:'sa3', fa:'سالاد با گوشت دونر', de:'Salat mit Dönerfleisch',  price:6},
  ]},
  { id:'doner', fa:'دونر', de:'Döner', type:'list', items:[
    {id:'dn1',  fa:'دونر مرغ',                   de:'Hähnchen Döner',          price:6   },
    {id:'dn2',  fa:'دونر گوساله',                de:'Rind Döner',              price:8   },
    {id:'dn3',  fa:'دونر مرغ XL',                de:'Hähnchen Döner XL',       price:7.5 },
    {id:'dn4',  fa:'دونر گوساله XL',             de:'Rind Döner XL',           price:9.5 },
    {id:'dn5',  fa:'دوروم مرغ',                  de:'Hähnchen Dürüm',          price:6.5 },
    {id:'dn6',  fa:'دوروم گوساله',               de:'Rind Dürüm',              price:8.5 },
    {id:'dn7',  fa:'پوم دونر مرغ',               de:'Pommes Döner Hähnchen',   price:6   },
    {id:'dn8',  fa:'پوم دونر گوساله',            de:'Pommes Döner Rind',       price:8   },
    {id:'dn9',  fa:'بشقاب دونر مرغ',             de:'Döner Teller Hähnchen',   price:9   },
    {id:'dn10', fa:'بشقاب دونر گوساله',          de:'Döner Teller Rind',       price:11  },
    {id:'dn11', fa:'پیتزای ترکی مرغ',            de:'Türkische Pizza Hähnchen',price:7   },
    {id:'dn12', fa:'پیتزای ترکی گوساله',         de:'Türkische Pizza Rind',    price:9   },
    {id:'dn13', fa:'پرس گوشت دونر مرغ',          de:'Döner Fleisch Hähnchen',  price:7   },
    {id:'dn14', fa:'پرس گوشت دونر مرغ XL',      de:'Döner Fleisch Hähnchen XL',price:10 },
    {id:'dn15', fa:'پرس گوشت دونر گوساله',       de:'Döner Fleisch Rind',      price:9   },
    {id:'dn16', fa:'پرس گوشت دونر گوساله XL',   de:'Döner Fleisch Rind XL',   price:12.5},
  ]},
  { id:'vegetarian', fa:'گیاهی', de:'Vegetarisch', type:'list', items:[
    {id:'vg1', fa:'دونر سبزیجات',        de:'Gemüse Döner',              price:6  },
    {id:'vg2', fa:'دوروم گیاهی',         de:'Vegetarisches Dürüm',       price:6.5},
    {id:'vg3', fa:'پیتزای ترکی با سالاد',de:'Türkische Pizza mit Salat', price:6.5},
    {id:'vg4', fa:'دوروم فلافل',         de:'Falafel Dürüm',             price:6.5},
    {id:'vg5', fa:'بشقاب فلافل',         de:'Falafel Teller',            price:8  },
    {id:'vg6', fa:'ساندویچ فلافل',       de:'Falafel Sandwich',          price:6  },
  ]},
  { id:'extras', fa:'اضافات', de:'Extras', type:'list', items:[
    {id:'ex1', fa:'سیب زمینی',          de:'Pommes',             price:3.5},
    {id:'ex2', fa:'سیب زمینی XL',       de:'Pommes XL',          price:5  },
    {id:'ex3', fa:'۶ ناگت مرغ',          de:'6 Hähnchen Nuggets', price:4  },
    {id:'ex4', fa:'۶ ناگت با سیب زمینی', de:'6 Nuggets mit Pommes',price:7.5},
    {id:'ex5', fa:'۸ استریپس مرغ',       de:'8 Hähnchen Strips',  price:5.5},
    {id:'ex6', fa:'سبزیجات گریل',        de:'Grillgemüse',        price:2  },
    {id:'ex7', fa:'گوشت اضافه',          de:'Extra Fleisch',      price:2  },
    {id:'ex8', fa:'پنیر اضافه',          de:'Extra Käse',         price:0.5},
    {id:'ex9', fa:'هالوپینو اضافه',      de:'Extra Jalapeño',     price:0.5},
  ]},
  { id:'sauces', fa:'سس‌ها', de:'Saucen', type:'sauces', items:[
    {id:'sc1',fa:'BBQ',         de:'BBQ',        price:1},
    {id:'sc2',fa:'آیولی',       de:'Aioli',      price:1},
    {id:'sc3',fa:'کاری',        de:'Curry',      price:1},
    {id:'sc4',fa:'سبزی',        de:'Kräuter',    price:1},
    {id:'sc5',fa:'شیرین‌ترش',   de:'Süß-Sauer',  price:1},
    {id:'sc6',fa:'سیر',         de:'Knoblauch',  price:1},
    {id:'sc7',fa:'مایونز',      de:'Mayonnaise', price:1},
    {id:'sc8',fa:'کچاپ',        de:'Ketchup',    price:1},
  ]},
  { id:'desserts', fa:'دسر', de:'Desserts', type:'card', items:[
    {id:'ds1',fa:'بستنی اسپاگتی',       de:'Spaghettieis',        price:3},
    {id:'ds2',fa:'بستنی زعفرانی ایرانی',de:'Persisches Safraneis',price:3},
  ]},
];
